service: mangoodb-function
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  stage: staging
  region: us-east-1
  memorySize: 128

package:
  exclude:
    - .gitignore
    - bitbucket-pipelines.yml
    - serverless.yml
    - tests/**
    - coverage/**
    - .env
  excludeDevDependencies: true
  individually: true

functions:
  mangoDBOperations:
    handler: handler.mangoDBOperations
    environment:
      MANGODB_CONNECT: mongodb+srv://mangooAI:2EmsljTfzHUpDS7h@mangodb.5aesw.mongodb.net/mangoDB
